### ISSUE TITLE
Make some actions editable by default

### ISSUE THREAD

**Issue by rickyson96** [mohkale/compile-multi#10]
Currently, my use case is that I have some `yarn` command that needs extra parameter to run. It is defined as `yarn test <module>`, which I'll then input the specific module and the test will only be ran for that module.

What do you think of enabling some kind of customization, either for specific module to default to edit the compile command (similar to running `M-x compile`)?

Other possibly easier solution that I can think of is either to put that as global configuration, or just disable `REQUIRE-MATCH` so that I can edit it on the `completing-read`.

Or if you have other solution to my specific needs that I missed?

Thank you!

**Comment by mohkale** [comment]
I'd recommend defining a command for this specific use case.

```elisp
(defun compile-multi-yarn-x (x)
  (interactive "sTarget: ")
  (compile (concat "yarn run " (shell-quote-argument x))))

(push `(t ("yarn-do" . #'compile-multi-yarn-x))
      compile-multi-config)
```

Although a general embark action like you did in your PR is also acceptable and likely to come in useful for others. Thanks. I'll review it tomorrow.

**Comment by mohkale** [comment]
Merged in with some slight refactorings. Thanks.
