### ISSUE TITLE
No way to run in comint mode

### ISSUE THREAD

**Issue by Gavinok** [mohkale/compile-multi#7]
Usually if a compile command requires user input you can simply call compile like so
`C-u M-x compile` however since compile is called without the comint argument `(compile compile-cmd)` as opposed to `(compile compile-cmd comint)` comint mode can not be entered.

As a result compile-multi does not support universal for entering comint mode  during compilation. so there is no simple way to allow for user input from compilation commands. Any ideas as to how I could allow for this?

**Comment by mohkale** [comment]
Should be fixed now. For context this will work for string based compile-multi commands. For others like the wrapped projection commands it will not because they actually run through the wrapped projection-commands-*-project command.
